# ============================================================
# KONFIGURASI UTAMA JEKYLL
# ============================================================
# File ini mengatur setelan global situs.
# Restart server jika mengubah file ini.

# --- Identitas Situs ---
title: "RandomWeeks"
email: "zeyshyy@gmail.com"
description: >-
  "Tidak selalu penting, tapi selalu nyata. Ruang sederhana untuk menulis hal-hal acak, 
  tentang ide, perasaan, dan hal-hal kecil yang membuat hidup terasa nyata."
baseurl: "" # Subpath situs (kosongkan jika di root)
url: "https://randomweeks.netlify.app" # Domain utama

# --- Sosial Media ---
facebook_username: "muhammadraidzaidani"
github_username:  "zidan-idz"

# --- Pengaturan Build ---
theme: "minima"
plugins:
  - "jekyll-feed"
  - "jekyll-seo-tag"
  - "jekyll-sitemap"

# Layout default untuk semua halaman
layout: 'default'

# --- Nilai Default (Front Matter) ---
defaults:
  - scope:
      path: "" # Berlaku untuk semua file
      type: posts
    values:
      author: admin

# --- Pengecualian (Exclude) ---
# Folder/file ini tidak akan diproses oleh Jekyll
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/

